origin: "https://localhost:8080"
endpoint: "webauthn"
handler:
  fumieval:
  - aaguid: 00000000000000000000000000000000
    credentialId: 57QNM7zVr77rN6mN-Z-ZVPnZgh4AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA==
    credentialPublicKey: pQECAyYgASFYICmf4vKOR013my0PhZ4IFHU5cAH4uRqnNLtuRLcyZEtUIlggpz_qkbKD1k1C4cNsHPvTCmddL-QG9bSgqs8JOAs3yG8=

timeout: 86400
