origin: "https://localhost:8080"
endpoint: "webauthn"
handler:
  fumi3:
  - aaguid: '00000000000000000000000000000000'
    credentialId: GKUYBIYJlF0cYpMRB31QXdACqN-vj_aW2cGdAXFPQ0NnFl27jFVlCKQ8GA4tVUt2K5Q9D2Qu0fW0EEUcsF-LCA==
    credentialPublicKey: pQECAyYgASFYIADyoIRl6IlLxC0lsh4T0LYAGFkW_r9gccOYbbHa3uXBIlggC8C7oYqVXzE30ALslSqajLu11NCn8GNAduBK6Qj0PqQ=

timeout: 86400
certStore: "demo/cacert.pem"