origin: "https://localhost:8080"
endpoint: "webauthn"
handler:
  fumieval:
  - credentialId: Nut-zVzvTl-UWjALG6CbqCVQ87Tv87ROA1JW4UhZU3A=
    publicKey: pAEDAzkBACBZAQDmdgyGiMU645izs0lH0708LkByr8LwvcfhGkqcvjMLPk_At7tdc0fK1_Fhy7SecZQdJQ2ZPAwcL60C4XFZWw0K3OXG2G05sZHA2-1_D1W91fsmltIWIwsKa6dhdJDtxk9ALGPzNWNw3pQ5HkcMQZMmMa2QuG_gZGI8Cfkq-4_QivgQ5QdgMgUFvNJR-Il886yBwL6W7l25G1qZaFqlNUOj_Gfac7Q0IyiRN5W4JbAyC77aQY2uAb2G8oUVoZRxv2H8rlnnO-HIsVny3eY6efqXhBgPq2Eu-RiiIpRKVkA0F3P1tvjwtzPihjxT0qHFSSDRF54r6PndlcrWsg7Jq9OJIUMBAAE=
timeout: 86400
